CREATE TABLE `risks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`createdByUserId` int NOT NULL,
	`macroprocessCode` varchar(100) NOT NULL,
	`riskCode` varchar(100) NOT NULL,
	`riskDescription` text NOT NULL,
	`riskEvent` text NOT NULL,
	`riskCategory` enum('Risco Estratégico','Risco Financeiro','Risco de Imagem','Risco Operacional','Risco de Conformidade','Risco de Integridade') NOT NULL,
	`financialConformityDescription` text,
	`impact` int NOT NULL,
	`probability` int NOT NULL,
	`inherentRisk` int NOT NULL,
	`inherentRiskLevel` varchar(50) NOT NULL,
	`internalControls` text NOT NULL,
	`controlEfficacy` enum('Inexistente','Fraco','Mediano','Satisfatório','Forte') NOT NULL,
	`residualRisk` float NOT NULL,
	`residualRiskLevel` varchar(50) NOT NULL,
	`riskCauses` text NOT NULL,
	`causeClassification` varchar(200),
	`causeCategory` enum('Falha Humana','Falha Tecnológica','Desvio de Conduta','Falha de Processo','Falha de Equipamentos ou Infraestrutura','Ação de Terceiros','Eventos da Natureza') NOT NULL,
	`riskConsequences` text NOT NULL,
	`consequenceClassification` varchar(200),
	`consequenceCategory` enum('Financeira','Reputacional','Operacional','Legal e Regulatória','Danos Ambientais','Danos Sociais') NOT NULL,
	`treatmentAction` enum('Aceitar','Monitorar','Mitigar','Escalonar') NOT NULL,
	`actionPlanDescription` text NOT NULL,
	`actionPlanDeadline` date,
	`actionPlanResponsible` varchar(200) NOT NULL,
	`actionPlanStatus` enum('Pendente','Em andamento','Concluído','Atrasado') NOT NULL DEFAULT 'Pendente',
	`suggestedDecision` enum('Aceitar','Monitorar','Mitigar','Escalonar') NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `risks_id` PRIMARY KEY(`id`)
);
